// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmrfefwqfeuffcauaqbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcmZlZndxZmV1ZmZjYXVhcWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODM4ODEsImV4cCI6MjA3NDY1OTg4MX0.hNEN6eUzMO_on7HoMxrjEevWyFqJwOhziYLBGc1tkAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});